import Head from "next/head"
import React from "react"
import FormTitle from "../form-title"
import FormTracker from "../form-tracker"

interface Props {
  children?: JSX.Element
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <div className="flex min-h-screen w-screen select-none flex-col bg-white text-slate-500 dark:bg-gray-800 dark:text-white">
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-12 mb-8 flex flex-1">{children}</div>
      <FormTitle currentStep={1} maxSteps={3} text="Basic Information" />
      <FormTracker currentStep={1} maxSteps={3} />
    </div>
  )
}

export default Layout
